### ISSUE TITLE
System.IO.FileLoadException

### ISSUE THREAD

**Issue by n0whereRuoxi** [davidezordan/CognitiveServicesSamples#2]
> System.IO.FileLoadException
>   HResult=0x80131040
>   Message=Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
>   Source=CognitiveServicesVisionLibrary
>   StackTrace:
>    at CognitiveServicesVisionLibrary.CognitiveVisionHelper.<AnalyzeImage>d__5.MoveNext() in D:\Hololens\CognitiveServicesSamples-master\CognitiveServicesSamples-master\CognitiveServicesVision\CognitiveServicesVisionLibrary\CognitiveVisionHelper.cs:line 49
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
>    at CognitiveServicesVisionLibrary.CognitiveVisionHelper.AnalyzeImage(StorageFile file)
>    at PhotoManager.<OnCapturedPhotoToDisk>d__13.MoveNext() in D:\Hololens\HololensUnity\Assets\Scripts\PhotoManager.cs:line 111
> 

Any idea how to fix this bug?

**Comment by davidezordan** [comment]
Which version of Unity are you using? I've tested it using Unity version 2017.2.1p4 and not able to reproduce your error.
Have you tried to update the NuGet package "Microsoft.NETCore.UniversalWindowsPlatform" to the latest version in the generated UWP project?
